name: Build

on:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Build app for release
        run: msbuild MahjongUtil/MahjongUtil.vcxproj -t:rebuild -property:Configuration=Release

      - name: Prepare for Upload
        run: |
          mkdir Release
          move MahjongUtil/Release/MahjongUtil.dll Release
          copy license.txt Release/license.txt
          copy readme.txt Release/readme.txt

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: MahjongUtil
          path: Release
